# -*- coding: utf-8 -*-
"""Copy of AI_Phase_3 (4).

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LxdKbpTUxfC7hr9vn5sp49xhCyJJHMDv

# **Artificial Intelligence - Phase 3**

# ChatBot Using Python

**To Do:**


*   Load Dataset
*   Preprocess Dataset
*  Perform Analysis
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""**Step 1**: Dataset Loading

 Here we load the dataset from our given URL
"""

# Load the dataset
dataset_path = '/content/dialogs.txt'
data = pd.read_csv(dataset_path, delimiter='\t', names=['User', 'Bot'])

"""**Step 2**: Dataset Overview"""

# Display the first few rows of the dataset
data.head()

"""**Step 3**: Data Analysis


In this section, we will perform some basic data analysis to gain insights into our dataset.

"""

# Check for missing values
missing_values = data.isnull().sum()
print("Missing Values:")
print(missing_values)

# Check the distribution of user and bot messages
user_message_count = len(data[data['User'].notnull()])
bot_message_count = len(data[data['Bot'].notnull()])
total_messages = len(data)
user_message_percentage = (user_message_count / total_messages) * 100
bot_message_percentage = (bot_message_count / total_messages) * 100

print(f"Total Messages: {total_messages}")
print(f"User Messages: {user_message_count} ({user_message_percentage:.2f}%)")
print(f"Bot Messages: {bot_message_count} ({bot_message_percentage:.2f}%)")

"""**Step 4**: Data Preprocessing

Now, we will preprocess the text data for use in our chatbot project. This typically involves text cleaning and tokenization.

"""

# Text cleaning and tokenization
data['User'] = data['User'].str.lower()
data['User'] = data['User'].apply(lambda x: x.split())
data['Bot'] = data['Bot'].str.lower()
data['Bot'] = data['Bot'].apply(lambda x: x.split())

"""SARAVANAN S

NANDHA COLLEGE OF TECHNOLOGY

21-10-2023

## Document Completion

We have successfully loaded and preprocessed the dataset for our chatbot project. The data analysis and preprocessing steps are essential for building a chatbot capable of understanding and responding to user input. Next, we can proceed with more advanced tasks like natural language processing and model development.
"""